+ [episode-0022, off stream] Add (experimental) retry for .app singing step.

diff --git a/.github/workflows/build_package_and_sign_macos.yaml b/.github/workflows/build_package_and_sign_macos.yaml
--- a/.github/workflows/build_package_and_sign_macos.yaml
+++ b/.github/workflows/build_package_and_sign_macos.yaml
@@ -285,13 +285,36 @@ jobs:
           security find-identity -v
 
       - name: Sign .app
+        id: sign0
+        continue-on-error: true
         run: |
-          echo ":TODO:"
           ping -c 5 time.apple.com
           cd ${{ env.PACKAGE_FOLDER}}
           codesign -s ${{ secrets.CODESIGN_CERT_IDENTITY }} -f -v --timestamp --options runtime rar-rs.app
 
         timeout-minutes: 10
+
+      - name: Sign .app (2nd try)
+        id: sign1
+        continue-on-error: true
+        if: steps.sign0.outcome=='failure'
+        run: |
+          sleep 60
+          ping -c 5 time.apple.com
+          cd ${{ env.PACKAGE_FOLDER}}
+          codesign -s ${{ secrets.CODESIGN_CERT_IDENTITY }} -f -v --timestamp --options runtime rar-rs.app
+
+        timeout-minutes: 10
+
+      - name: Set Sign status
+        if: always()
+        run: |
+          if ${{ steps.sign0.outcome=='success' || steps.sign1.outcome=='success' }}; then
+             echo "Successfully signed!"
+          else
+            echo "Failed signing even after retry"
+             exit 1
+          fi
 
       - name: Create archive
         run: |
